(function(a){a.ebay=a.ebay||{};a.ebay.follow=a.ebay.follow||{}})(window);(function(a){a.ebay.follow.Config={PROXY_HOST:"http://svcs.ebay.com",FOLLOW_SERVICE_HOST:"http://www.mbeupdater.vip.ebay.com",INTEREST_SERVICE_HOST:"http://feedsvcr.vip",WEBCOMMAND_SERVICE_HOST:"http://www.ebay.com",FEED_URL:"http://www.ebay.com",PROFILE_URL:"http://www.ebay.com/usr/{username}",PRIVACY_URL:"http://www.ebay.com/usr/{username}/all-follows?priflwtype={type}#{type}",LOGIN_HOST:"https://signin.ebay.com"}})(window);
(function(a){a.ebay.follow.Strings={BUTTON_FOLLOW:"Follow",BUTTON_FOLLOWING:"Following",BUTTON_UNFOLLOW:"Unfollow",LINK_FOLLOW_PERSON:"Follow this seller",LINK_FOLLOWING_PERSON:"Following this seller",LINK_UNFOLLOW_PERSON:"Unfollow this seller",LINK_FOLLOW_INTEREST:"Follow this search",LINK_FOLLOWING_INTEREST:"Following this search",LINK_UNFOLLOW_INTEREST:"Unfollow this search",OVERLAY_FOLLOW_PERSON:"Like this member's picks? Follow to see more in your eBay feed.",OVERLAY_FOLLOWED_PERSON:"Great! You're now following {name} in your {feed}.{icon}Following this member is {privacy}. Change your {privacypreferences}.",
OVERLAY_UNFOLLOW_PERSON:"Unfollow to stop seeing updates from {name} in your eBay feed.",OVERLAY_FOLLOW_INTEREST:"Passionate about this interest? Follow to see more in your eBay feed.",OVERLAY_FOLLOWED_INTEREST:"Nice! Now you're following this interest in your {feed}.{icon}Following this interest is {privacy}. Change your {privacypreferences}.",OVERLAY_UNFOLLOW_INTEREST:"Unfollow to stop seeing updates from this interest in your eBay feed.",OVERLAY_FOLLOW_COLLECTION:"Like this collection? Follow to see updates in your eBay feed.",
OVERLAY_FOLLOWED_COLLECTION:"Nice! Now you're following this collection in your {feed}.{icon}Following this collection is {privacy}. Change your {privacypreferences}.",OVERLAY_UNFOLLOW_COLLECTION:"Unfollow to stop seeing updates from this collection in your eBay feed.",OVERLAY_LABEL_EMAIL:"Email me new items that match this interest",OVERLAY_LABEL_PRIVACY:"Visible only to me",OVERLAY_LINK_FEED:"eBay feed",OVERLAY_LINK_PROFILE:"profile",OVERLAY_LINK_PRIVACY:"privacy preferences",ERROR:"Sorry, we encountered an internal error. Please try again later.",
ERROR_MAX_INTERESTS:"You need to unfollow some interests before you can follow another. Go to your {profile}.",PRIVATE:"private",PUBLIC:"public",DISCOVERY:"Follow to see new listings in your eBay feed and get email alerts."}})(window);
(function(a){a.ebay.follow.Constants={ENTITY_COLLECTION:"collection",ENTITY_PERSON:"person",ENTITY_INTEREST:"interest",DATA_USER_ID:"data-userId",DATA_FOLLOWING:"data-following",DATA_ENTITY_TYPE:"data-entityType",DATA_ENTITY_NAME:"data-entityName",DATA_ENTITY_ID:"data-entityId",DATA_INTEREST_ID:"data-interestId",DATA_CSRF:"data-csrf",DATA_PAGE_ID:"data-pageId",DATA_MODULE_ID:"data-moduleId",DATA_SEARCH_URL:"data-searchUrl",DATA_VISIBILITY:"data-visibility",DATA_DISCOVERY_ENABLED:"data-discoveryEnabled",
DATA_SHORT_LINK_TEXT:"data-shortLinkText",DATA_HIDE_OVERLAY:"data-hideOverlay",SEARCH_PARAM_CSRF:"fol",SERVICE_TIMEOUT:3E3,TRACKING_ID_FOLLOW:4741,TRACKING_ID_UNFOLLOW:4742,TRACKING_ID_EMAILOPTIN:4743,TRACKING_ID_EMAILOPTOUT:4744,TRACKING_ID_FEED:4745,TRACKING_ID_PROFILE:4746,TRACKING_FOL_TYPE:{COLLECTION:"0",PERSON:"1",INTEREST:"2"},ERROR_CODE_AUTH:"0",ERROR_CODE_CSRF:"1",ERROR_CODE_DEFAULT:"100",KEY_ENTER:13,KEY_SPACE:32,EVENT_EMAIL_OPTIN:"emailoptin",EVENT_EMAIL_OPTOUT:"emailoptout",PRIVACY_TYPE_MAPPING:{collection:"collection",
person:"people",interest:"interest"}}})(window);
(function(a,n){var c=n.ebay.follow.Constants,v=n.ebay.follow.Strings,s=n.ebay.follow.Config,p=/{feed}|{name}|{profile}|{icon}|{privacy}|{privacypreferences}/g;n.ebay.follow.Util={getSearchParams:function(){var i={};a.each(window.location.search.substring(1).split("&"),function(b,g){i[g.split("=")[0]]=g.split("=")[1]});return i},parseDataAttributes:function(i){var b=a(i);return{userId:b.attr(c.DATA_USER_ID)||"",entityType:b.attr(c.DATA_ENTITY_TYPE)||"DEFAULT",entityName:b.attr(c.DATA_ENTITY_NAME)||
null,entityId:b.attr(c.DATA_ENTITY_ID)||null,interestId:b.attr(c.DATA_INTEREST_ID)||null,csrf:b.attr(c.DATA_CSRF)||null,pageId:b.attr(c.DATA_PAGE_ID)||null,moduleId:b.attr(c.DATA_MODULE_ID)||null,searchUrl:b.attr(c.DATA_SEARCH_URL)||null,visibility:b.attr(c.DATA_VISIBILITY)||"public",discoveryEnabled:b.attr(c.DATA_DISCOVERY_ENABLED)==="yes",shortLinkText:b.attr(c.DATA_SHORT_LINK_TEXT)==="yes",hideOverlay:b.attr(c.DATA_HIDE_OVERLAY)==="yes"}},lintData:function(){return null},truncateText:function(i,
b){return i&&i.length>b?i.substr(0,b-3)+"...":i},createSpan:function(i){return a("<span/>").text(i)},createLink:function(i,b,g){return a("<a/>").text(i).attr("href",b).attr("_sp",g)},createBold:function(i){return a("<strong/>").text(this.truncateText(i,40))},createIcon:function(i){var b="fol-privacy-icon"+(i?"":" fol-privacy-icon-lock");return a('<br/><br/><span class="'+b+'"></span>')},compileTextPattern:function(i,b,g,f,h,k,l){for(var e=a(),o=i.replace(p,function(q){return"|||"+q+"|||"}).split("|||"),
t=0;t<o.length;t++){var w=o[t];if(p.test(w))if(w==="{name}")e=e.add(this.createBold(b));else if(w==="{feed}")e=e.add(this.createLink(v.OVERLAY_LINK_FEED,s.FEED_URL,h));else if(w==="{profile}")e=e.add(this.createLink(v.OVERLAY_LINK_PROFILE,s.PROFILE_URL.replace("{username}",f),k));else if(w==="{icon}")e=e.add(this.createIcon(l));else if(w==="{privacy}")e=e.add(this.createSpan(l?v.PUBLIC:v.PRIVATE));else{if(w==="{privacypreferences}"){var j=c.PRIVACY_TYPE_MAPPING[g];e=e.add(this.createLink(v.OVERLAY_LINK_PRIVACY,
s.PRIVACY_URL.replace("{username}",f).replace(/{type}/g,j),k))}}else e=e.add(this.createSpan(w))}return e},hrefHasParams:function(i){return/\?/.test(i)},constructTrackingSid:function(i,b,g){var f="";if(i){f+="p"+i;if(b)f+=".m"+b;if(g)f+=".l"+g}return f}}})(jQuery,window);
(function(a){var n=a.ebay.follow.Config,c=a.ebay.follow.Constants,v='{"user":{"id":"{USER_ID}","type":"USERNAME","convert_to":"ACCOUNT_ID"}}',s=function(e){return encodeURIComponent(v.replace("{USER_ID}",e))},p=function(e,o){return encodeURIComponent("{SERVICE_HOST}/merchbupd/v0/feed/users/{user}/follows/COLLECTION/{ENTITY_ID}".replace("{SERVICE_HOST}",e).replace("{ENTITY_ID}",o))},i=function(e,o){return encodeURIComponent('{"user":{"id":"{USER_ID}","type":"USERNAME","convert_to":"ACCOUNT_ID"}, "person":{"id":"{ENTITY_ID}","type":"USERNAME","convert_to":"ACCOUNT_ID"}}'.replace("{USER_ID}",
e).replace("{ENTITY_ID}",o))},b=function(e){return encodeURIComponent("{SERVICE_HOST}/merchbupd/v0/feed/users/{user}/follows/USER/{person}".replace("{SERVICE_HOST}",e))},g=function(e){return encodeURIComponent('{"user":{"id":"{USER_ID}","type":"USERNAME","convert_to":"ACCOUNT_ID"}}'.replace("{USER_ID}",e))},f=function(e,o,t){return encodeURIComponent("{SERVICE_HOST}/merchbupd/v0/feed/users/{user}/follows/INTEREST/{ENTITY_ID}".replace("{SERVICE_HOST}",e).replace("{ENTITY_ID}",t))},h=function(e,o){return encodeURIComponent("{SERVICE_HOST}/feedservice/interestservice/v1/ss/interest-id?url={SAVED_SEARCH_URL}".replace("{SERVICE_HOST}",
e).replace("{SAVED_SEARCH_URL}",encodeURIComponent(o)))},k=function(e,o,t,w,j){return"{PROXY_HOST}/proxy?method={METHOD}&_csrf={CSRF}&data={DATA}&url={SERVICE_URL}".replace("{PROXY_HOST}",e).replace("{SERVICE_URL}",o).replace("{METHOD}",t).replace("{CSRF}",w).replace("{DATA}",j)},l=function(e,o,t,w,j){var q,u;if(w.toLowerCase()===c.ENTITY_COLLECTION){q=p(n.FOLLOW_SERVICE_HOST,t);u=s(o)}else if(w.toLowerCase()===c.ENTITY_PERSON){q=b(n.FOLLOW_SERVICE_HOST);u=i(o,t)}else{q=f(n.FOLLOW_SERVICE_HOST,o,
t);u=g(o)}return k(n.PROXY_HOST,q,e,j,u)};a.ebay.follow.ProxyService={callService:function(e,o,t,w,j){var q=l(e,o,t,w,j),u=$.Deferred(),y=$.ajax(q,{dataType:"jsonp",timeout:c.SERVICE_TIMEOUT});y.done(function(x){if(x.okay===true)u.resolve();else{var A=c.ERROR_CODE_DEFAULT,z=x.errorMessage;if(z)A=z.error[0].errorId;u.reject(A)}});y.fail(function(){u.reject(c.ERROR_CODE_DEFAULT)});return u.promise()},getInterestId:function(e,o){var t=h(n.INTEREST_SERVICE_HOST,e),w=k(n.PROXY_HOST,t,"GET",o,""),j=$.Deferred(),
q=$.ajax(w,{dataType:"jsonp",timeout:c.SERVICE_TIMEOUT});q.done(function(u){u.okay===true?j.resolve(u.data):j.reject(u.errorMessage)});q.fail(function(){j.reject()});return j.promise()}}})(window);
(function(a){var n=a.ebay.follow.Config,c=a.ebay.follow.Constants,v="{SERVICE_HOST}/sch/favsearch?_efs=true&emailme={EMAIL_FLAG}&savedsearch={SEARCH_URL}&csrf={CSRF}&searchname={ENTITY_NAME}&ssid={ENTITY_ID}&mode=2&visibility={VISIBILITY}",s=function(b,g,f,h,k,l,e){return v.replace("{SERVICE_HOST}",b).replace("{EMAIL_FLAG}",g).replace("{SEARCH_URL}",encodeURIComponent(f)).replace("{CSRF}",h).replace("{ENTITY_NAME}",encodeURIComponent(k)).replace("{ENTITY_ID}",l).replace("{VISIBILITY}",e)},p=function(b,
g,f,h,k,l){l=l===0||l===1?l:"";return"{SERVICE_HOST}/sch/favsearch?_efs=true&emailme={EMAIL_FLAG}&savedsearch={SEARCH_URL}&csrf={CSRF}&searchname={ENTITY_NAME}&replaceid={ENTITY_ID}&mode=3".replace("{SERVICE_HOST}",b).replace("{EMAIL_FLAG}",l).replace("{SEARCH_URL}",encodeURIComponent(g)).replace("{CSRF}",f).replace("{ENTITY_NAME}",encodeURIComponent(k)).replace("{ENTITY_ID}",h)},i=function(b,g,f){return"{SERVICE_HOST}/sch/favsearch?_efs=true&csrf={CSRF}&replaceid={ENTITY_ID}&mode=4".replace("{SERVICE_HOST}",
b).replace("{CSRF}",g).replace("{ENTITY_ID}",f)};a.ebay.follow.WebcommandService={callService:function(b){var g=$.Deferred(),f=$.ajax(b,{crossDomain:true,dataType:"jsonp",timeout:c.SERVICE_TIMEOUT});f.done(function(h){var k=h.model||{};if(k.status==="success")g.resolve({ssid:k.m_searchId.toString()||null});else k.isSignedIn===false?g.reject(c.ERROR_CODE_AUTH):g.reject(c.ERROR_CODE_DEFAULT)});f.fail(function(){g.reject(c.ERROR_CODE_DEFAULT)});return g.promise()},getFollowUrl:function(b,g,f,h,k,l){return s(n.WEBCOMMAND_SERVICE_HOST,
b,g,f,h,k,l)},getUnfollowUrl:function(b,g){return i(n.WEBCOMMAND_SERVICE_HOST,b,g)},getUpdateUrl:function(b,g,f,h,k){return p(n.WEBCOMMAND_SERVICE_HOST,b,g,f,h,k)},emailOptIn:function(b,g,f,h){return this.callService(this.getUpdateUrl(f,g,b,h,1))},emailOptOut:function(b,g,f,h){return this.callService(this.getUpdateUrl(f,g,b,h,0))}}})(window);
(function(a){var n=a.ebay.follow.WebcommandService,c=a.ebay.follow.ProxyService,v=a.ebay.follow.Constants,s=function(i,b,g){return b===v.ENTITY_INTEREST&&(i||g)},p=function(i,b,g,f,h,k){var l=$.Deferred(),e=n.callService(n.getFollowUrl(1,f,b,h,"",k.toUpperCase()));e.done(function(o){c.callService("DELETE",i,g,v.ENTITY_INTEREST,b).done(function(){l.resolve(o)}).fail(function(){l.reject(o)})});e.fail(function(o){l.reject(o)});return l.promise()};a.ebay.follow.Service={follow:function(i,b,g,f,h,k,l,
e){return s(b,f,k)?n.callService(n.getFollowUrl(1,k,h,g,b,e)):c.callService("PUT",i,b,f,h)},unfollow:function(i,b,g,f,h,k,l){if(s(b,f,false))return n.callService(n.getUnfollowUrl(h,b));else{var e=f===v.ENTITY_INTEREST?b||l:b;return c.callService("DELETE",i,e,f,h)}},updateInterest:function(i,b,g,f,h,k,l){var e=$.Deferred(),o;o=g?n.callService(n.getUpdateUrl(h,b,g,k)):p(i,b,f,h,k,l);o.done(function(t){c.getInterestId(h,b).done(function(w){t.interestId=w.interestId;e.resolve(t)}).fail(function(){e.reject(t)})});
o.fail(function(t){e.reject(t)});return e.promise()}}})(window);
(function(a,n){var c=n.ebay.follow.Constants,v=n.ebay.follow.Strings,s=380,p,i=function(){if(this.overlayHideTimer!==null){window.clearTimeout(this.overlayHideTimer);this.overlayHideTimer=null}},b=function(){this.hide(10)},g=function(){this.hide()},f=function(j){j.keyCode===c.KEY_ENTER&&this.hide()},h=function(j){if(a(j.target).is(":checked")){this.$checkbox.addClass("fol-checkbox-checked");a(this).trigger(c.EVENT_EMAIL_OPTIN)}else{this.$checkbox.removeClass("fol-checkbox-checked");a(this).trigger(c.EVENT_EMAIL_OPTOUT)}},
k=function(j){if(j.keyCode===c.KEY_SPACE){j.preventDefault();var q=this.$checkbox.find("input");if(q.attr("checked")){q.removeAttr("checked");this.$checkbox.removeClass("fol-checkbox-checked");a(this).trigger(c.EVENT_EMAIL_OPTOUT)}else{q.attr("checked","checked");this.$checkbox.addClass("fol-checkbox-checked");a(this).trigger(c.EVENT_EMAIL_OPTIN)}}},l=function(j,q){var u=a('<li class="fol-checkbox-checked"><input type="checkbox" checked></input><label><span class="fol-checkbox-icon" tabindex="0"></span><span class="fol-text"></span></label></li>'),
y=u.find("label");u.find("input").attr("id",q);y.attr("for",q).find(".fol-text").text(j);return u},e=function(){this.overlayHideTimer=null;this.$el.find("a").off("focusin",this.onChildFocusInProxy);this.$el.find("a").off("focusout",this.onChildFocusOutProxy);this.$el.fadeOut("fast");if(this===p)p=null},o=function(){if(this.overlayHideTimer!==null){window.clearTimeout(this.overlayHideTimer);this.overlayHideTimer=null}},t=function(j){var q=j.left,u=a(window).width();if(q+s+50>u)q=u-s-50;return{left:q,
top:j.top,notchLeft:j.left+35-q}},w=function(j){this.$el.find(".fol-olay-inner-notch").css("left",j);this.$el.find(".fol-olay-outer-notch").css("left",j)};n.ebay.follow.WidgetOverlay=function(j,q){this.enabled=q;this.$el=a('<div class="fol-olay"><span class="fol-olay-outer-notch"></span><span class="fol-olay-inner-notch"></span><span class="fol-error-icon"></span><span class="fol-close" tabIndex="0"></span><p></p><ul></ul></div>').appendTo(j);this.$close=this.$el.find(".fol-close");this.$checkbox=
l(v.OVERLAY_LABEL_EMAIL,j.prop("id")+"-checkbox").appendTo(this.$el.find("ul"));this.overlayHideTimer=null;this.onMouseOverProxy=a.proxy(o,this);this.onCloseClickProxy=a.proxy(g,this);this.onCloseKeyUpProxy=a.proxy(f,this);this.onCheckboxClickProxy=a.proxy(h,this);this.onCheckboxKeypressProxy=a.proxy(k,this);this.onChildFocusInProxy=a.proxy(i,this);this.onChildFocusOutProxy=a.proxy(b,this);this.$el.on("mouseover",this.onMouseOverProxy);this.$close.on("click",this.onCloseClickProxy);this.$close.on("keyup",
this.onCloseKeyUpProxy);this.$close.on("focusin",this.onChildFocusInProxy);this.$close.on("focusout",this.onChildFocusOutProxy);this.$checkbox.on("focusin",this.onChildFocusInProxy);this.$checkbox.on("focusout",this.onChildFocusOutProxy);this.$checkbox.find("input").on("click",this.onCheckboxClickProxy);this.$checkbox.find(".fol-checkbox-icon").on("keypress",this.onCheckboxKeypressProxy)};n.ebay.follow.WidgetOverlay.prototype={cancelHide:function(){if(this.overlayHideTimer!==null){window.clearTimeout(this.overlayHideTimer);
this.overlayHideTimer=null}},destroy:function(){this.$el.off("mouseover",this.onMouseOverProxy);this.$close.off("click",this.onCloseClickProxy);this.$close.off("keyup",this.onCloseKeyUpProxy);this.$close.off("focusin",this.onChildFocusInProxy);this.$checkbox.off("focusin",this.onChildFocusInProxy);this.$checkbox.find("input").off("click",this.onCheckboxClickProxy);this.$checkbox.find(".fol-checkbox-icon").off("keypress",this.onCheckboxKeypressProxy);this.$el.find("a").off("focusin",this.onChildFocusInProxy);
this.$el.find("a").off("focusout",this.onChildFocusOutProxy)},hide:function(j){if(this.overlayHideTimer===null||!j)this.overlayHideTimer=window.setTimeout(a.proxy(e,this),j||0)},show:function(j,q,u,y,x,A){if(this.enabled){this.setText(q);this.$el.find("ul").toggle(y);this.$el.toggleClass("fol-error",x);this.wasPostClick=A;this.$el.find("a").on("focusin",this.onChildFocusInProxy);this.$el.find("a").on("focusout",this.onChildFocusOutProxy);var z=t(u);w.call(this,z.notchLeft);if(!x&&p!==this){p&&p.hide();
p=this}else if(x&&p===this)p=null;return this.$el.appendTo(j).css({left:z.left,top:z.top}).fadeIn("fast")}},isVisible:function(){return this.$el.is(":visible")},isCheckboxVisible:function(){return this.$checkbox.is(":visible")},isCloseButtonVisible:function(){return this.$close.is(":visible")},hasTabIndex:function(){return this.$el.find("a").length>0||this.isCheckboxVisible()||this.isCloseButtonVisible()},setText:function(j){this.$el.find("p").html(j)},isPostClick:function(){return this.wasPostClick},
isErrorOverlay:function(){return this.$el.hasClass("fol-error")}}})(jQuery,window);
(function(a,n){var c=ebay.follow.Constants,v=ebay.follow.Config,s=ebay.follow.Strings,p=ebay.follow.Util,i=ebay.follow.WidgetOverlay,b=ebay.follow.Service,g=ebay.follow.WebcommandService,f="{LOGIN_HOST}/ws/ebayISAPI.dll?SignIn&ru={REDIRECT_URL}",h=30,k={FOLLOWED:"FOLLOWED",UNFOLLOW:"UNFOLLOW",FOLLOW:"FOLLOW"},l={UNFOLLOW:"fol-unfollow",FOLLOWED:"fol-followed",BUSY:"fol-busy"},e=false,o=function(){var d=this.getDictString(this.getState(),this.getEntityType().toUpperCase(),this.getElementType());this.setText(d)},
t=function(){var d=this.$btn,m=this.$el.hasClass("fol-flex")?"100%":d.outerWidth(),r=d.outerHeight();d.addClass(l.BUSY);if(d.prop("tagName")==="BUTTON"){d.css("display","inline-block");d.css("width",m);d.css("height",r)}},w=function(){var d=this.$btn,m=this.$el.hasClass("fol-flex")?"100%":"auto";d.removeClass(l.BUSY);if(d.prop("tagName")==="BUTTON"){d.css("width",m);d.css("height","auto");d.css("display","inlne")}},j=function(d){switch(d){case c.ERROR_CODE_AUTH:window.location=this.getLoginUrl();
break;default:this.olay.show(this.$el,this.getOverlayString("ERROR","DEFAULT"),this.getOverlayOffset(),false,true,true)}a(this).trigger("error",{entityId:this.dataAttrs.entityId,entityType:this.dataAttrs.entityType})},q=function(){w.call(this);this.$btn.removeAttr("aria-busy");this.$btn.on("click",this.onClickProxy);o.call(this)},u=function(d){var m=this.getEntityType(),r=this.getOverlayString(k.FOLLOWED,m);r=p.compileTextPattern(r,this.getEntityName(),this.getEntityType(),this.getUserId(),this.feedTrackingSid,
this.profileTrackingSid,this.isPublic());this.$btn.addClass(l.FOLLOWED);if(m===c.ENTITY_INTEREST&&d&&d.ssid){this.$el.attr("data-entityId",d.ssid);this.dataAttrs.entityId=d.ssid}this.$btn.attr("aria-pressed",true);this.olay.show(this.$el,r,this.getOverlayOffset(),m===c.ENTITY_INTEREST,false,true);a(this).trigger("follow",{entityId:this.dataAttrs.entityId,entityType:this.dataAttrs.entityType});if(this.getEntityId())a(document).trigger("rover",{sid:this.followTrackingSid,folid:this.getSearchUrl()||
this.getEntityId(),foltype:c.TRACKING_FOL_TYPE[m.toUpperCase()]})},y=function(d){var m=this.getEntityType(),r=this.getOverlayString(k.FOLLOW,m);r=p.compileTextPattern(r,this.getEntityName(),this.getEntityType(),this.getUserId(),this.feedTrackingSid,this.profileTrackingSid,this.isPublic());this.$btn.removeClass(l.UNFOLLOW);this.$btn.removeClass(l.FOLLOWED);this.$btn.attr("aria-pressed",false);if(m===c.ENTITY_INTEREST&&d&&d.ssid){this.$el.removeAttr("data-entityId");this.dataAttrs.entityId=null}this.olay.show(this.$el,
r,this.getOverlayOffset(),false,false,true);a(this).trigger("unfollow",{entityId:this.dataAttrs.entityId,entityType:this.dataAttrs.entityType});this.getEntityId()&&a(document).trigger("rover",{sid:this.unfollowTrackingSid,folid:this.getEntityId(),foltype:c.TRACKING_FOL_TYPE[m.toUpperCase()]})},x=function(){t.call(this);this.ajaxRequest=b.follow(this.dataAttrs.userId,this.dataAttrs.entityId,this.dataAttrs.entityName,this.dataAttrs.entityType,this.dataAttrs.csrf,this.dataAttrs.searchUrl,this.getInterestId(),
this.getVisibility());this.ajaxRequest.done(a.proxy(u,this));this.ajaxRequest.fail(a.proxy(j,this));this.ajaxRequest.always(a.proxy(q,this))},A=function(){t.call(this);this.ajaxRequest=b.unfollow(this.dataAttrs.userId,this.dataAttrs.entityId,this.dataAttrs.entityName,this.dataAttrs.entityType,this.dataAttrs.csrf,this.dataAttrs.searchUrl,this.getInterestId());this.ajaxRequest.done(a.proxy(y,this));this.ajaxRequest.fail(a.proxy(j,this));this.ajaxRequest.always(a.proxy(q,this))},z=function(){var d=this.getOverlayString(this.getState(),
this.getEntityType()),m=p.compileTextPattern(d,this.getEntityName(),this.getEntityType(),this.getUserId(),this.feedTrackingSid,this.profileTrackingSid,this.isPublic());this.overlayShowTimer=null;this.olay.isVisible()||this.olay.show(this.$el,m,this.getOverlayOffset(),false,false,false)},D=function(){this.olay.cancelHide();if(this.isOn()){this.$btn.addClass(l.UNFOLLOW);o.call(this)}if(this.overlayShowTimer===null)this.overlayShowTimer=window.setTimeout(a.proxy(z,this),600)},E=function(){this.$btn.removeClass(l.UNFOLLOW);
window.clearTimeout(this.overlayShowTimer);this.overlayShowTimer=null;this.olay.isErrorOverlay()||this.olay.hide(this.olay.isPostClick()?6E3:600);o.call(this)},F=function(){if(!e){this.olay.cancelHide();if(this.isOn()){this.$btn.addClass(l.UNFOLLOW);o.call(this)}var d=this.getOverlayString(this.getState(),this.getEntityType());this.olay.show(this.$el,p.compileTextPattern(d,this.getEntityName(),this.getEntityType(),this.getUserId(),this.feedTrackingSid,this.profileTrackingSid,this.isPublic()),this.getOverlayOffset(),
false,false,false)}},G=function(){this.$btn.removeClass(l.UNFOLLOW);this.olay.hide(10);o.call(this)},B=function(d){d.preventDefault();window.clearTimeout(this.overlayShowTimer);this.overlayShowTimer=null;this.$btn.off("click",this.onClickProxy);this.$btn.attr("aria-busy",true);if(this.isLoggedIn())this.isOn()?A.call(this):x.call(this);else window.location=this.getLoginUrl()},H=function(){e=true},I=function(){e=false},J=function(d){d.keyCode===c.KEY_SPACE&&B.call(this,d)},K=function(){g.emailOptIn(this.getEntityId(),
this.getCsrf(),this.getSearchUrl(),this.getEntityName());a(document).trigger("rover",{sid:this.emailOptInTrackingSid})},L=function(){g.emailOptOut(this.getEntityId(),this.getCsrf(),this.getSearchUrl(),this.getEntityName());a(document).trigger("rover",{sid:this.emailOptOutTrackingSid})},M=function(d,m,r){return"{HREF}{URL_SYMBOL}{CSRF_PARAM_KEY}={CSRF_PARAM_VALUE}#{WIDGET_ID}".replace("{HREF}",d).replace("{URL_SYMBOL}",p.hrefHasParams(d)?"&":"?").replace("{CSRF_PARAM_KEY}",c.SEARCH_PARAM_CSRF).replace("{CSRF_PARAM_VALUE}",
r).replace("{WIDGET_ID}",m)},N=function(d,m){return f.replace("{LOGIN_HOST}",d).replace("{REDIRECT_URL}",m)};n.ebay.follow.Widget=function(d){this.$el=a(d);this.$btn=this.$el.find("button, a");this.dataAttrs=this.$el.data("follow")||p.parseDataAttributes(d);this.olay=new i(this.$el,!this.getHideOverlay());this.isOn()&&this.$btn.addClass(l.FOLLOWED);this.ajaxRequest=this.overlayShowTimer=null;var m=this.getPageId(),r=this.getModuleId();this.followTrackingSid=p.constructTrackingSid(m,r,c.TRACKING_ID_FOLLOW);
this.unfollowTrackingSid=p.constructTrackingSid(m,r,c.TRACKING_ID_UNFOLLOW);this.emailOptInTrackingSid=p.constructTrackingSid(m,r,c.TRACKING_ID_EMAILOPTIN);this.emailOptOutTrackingSid=p.constructTrackingSid(m,r,c.TRACKING_ID_EMAILOPTOUT);this.feedTrackingSid=p.constructTrackingSid(m,r,c.TRACKING_ID_FEED);this.profileTrackingSid=p.constructTrackingSid(m,r,c.TRACKING_ID_PROFILE);this.onMouseEnterProxy=a.proxy(D,this);this.onMouseLeaveProxy=a.proxy(E,this);this.onFocusInProxy=a.proxy(F,this);this.onFocusOutProxy=
a.proxy(G,this);this.onClickProxy=a.proxy(B,this);this.onMouseDownProxy=a.proxy(H,this);this.onMouseUpProxy=a.proxy(I,this);this.onLinkKeyPressProxy=a.proxy(J,this);this.onEmailOptInProxy=a.proxy(K,this);this.onEmailOptOutProxy=a.proxy(L,this);this.$btn.on("mouseenter",this.onMouseEnterProxy);this.$el.on("mouseleave",this.onMouseLeaveProxy);this.$btn.on("focusin",this.onFocusInProxy);this.$btn.on("focusout",this.onFocusOutProxy);this.$btn.on("click",this.onClickProxy);this.$btn.on("mousedown",this.onMouseDownProxy);
this.$btn.on("mouseup",this.onMouseUpProxy);a(this.olay).on(c.EVENT_EMAIL_OPTIN,this.onEmailOptInProxy);a(this.olay).on(c.EVENT_EMAIL_OPTOUT,this.onEmailOptOutProxy);this.$btn.attr("role","button");this.$btn.attr("aria-pressed",this.isOn());if(this.isLink()){this.$btn.attr("tabIndex",0);this.$btn.attr("href","#");this.$btn.on("keypress",this.onLinkKeyPressProxy)}};n.ebay.follow.Widget.prototype={destroy:function(){this.$btn.off("mouseover",this.onMouseEnterProxy);this.$el.off("mouseleave",this.onMouseLeaveProxy);
this.$btn.off("focusin",this.onFocusInProxy);this.$btn.off("focusout",this.onFocusOutProxy);this.$btn.off("click",this.onClickProxy);this.$btn.off("keypress",this.onLinkKeyPressProxy);a(this.olay).off(c.EVENT_EMAIL_OPTIN,this.onEmailOptInProxy);a(this.olay).off(c.EVENT_EMAIL_OPTOUT,this.onEmailOptOutProxy)},setText:function(d){this.$btn.find("span:last").text(d)},isOn:function(){return this.$btn.hasClass(l.FOLLOWED)},isLink:function(){return this.getElementType()==="LINK"},isLoggedIn:function(){return this.dataAttrs.userId!==
""},getState:function(){var d;return d=this.$btn.hasClass(l.UNFOLLOW)?k.UNFOLLOW:this.isOn()?k.FOLLOWED:k.FOLLOW},isPublic:function(){return this.getVisibility()==="public"},getUserId:function(){return this.dataAttrs.userId||""},getElementType:function(){return this.$btn.prop("tagName").toLowerCase()==="a"?"LINK":this.$btn.prop("tagName").toUpperCase()},getEntityType:function(){return this.dataAttrs.entityType},getEntityName:function(){return this.dataAttrs.entityName},getEntityId:function(){return this.dataAttrs.entityId},
getInterestId:function(){return this.dataAttrs.interestId},getModuleId:function(){return this.dataAttrs.moduleId},getPageId:function(){return this.dataAttrs.pageId},getCsrf:function(){return this.dataAttrs.csrf},getSearchUrl:function(){return this.dataAttrs.searchUrl},getVisibility:function(){return this.dataAttrs.visibility||"public"},getDiscoveryEnabled:function(){return this.dataAttrs.discoveryEnabled},getIsShortLinkText:function(){return this.dataAttrs.shortLinkText},getHideOverlay:function(){return this.dataAttrs.hideOverlay},
getDictString:function(d,m,r){var C;if(d==="FOLLOWED")d="FOLLOWING";C=r==="BUTTON"||this.getIsShortLinkText()?["BUTTON",d].join("_"):[r,d,m].join("_");return s[C]},getOverlayString:function(d,m){var r;r=d==="ERROR"?"ERROR":["OVERLAY",d.toUpperCase(),m.toUpperCase()].join("_");return s[r]},getLoginUrl:function(){var d=this.$el.prop("id"),m=this.dataAttrs.csrf,r=window.location.hash?window.location.href.substring(0,window.location.href.indexOf("#")):window.location.href;m=M(r,d,m);m=encodeURIComponent(m);
return N(v.LOGIN_HOST,m)},getOverlayOffset:function(){var d=this.$btn.position();this.$btn.height();var m=d.left,r=d.top+this.$btn.height()+h;if(this.getElementType()==="LINK"){m-=13;r-=13}return{left:m,top:r}},setCsrf:function(d){this.dataAttrs.csrf=d},follow:function(){this.isOn()===false&&x.call(this)},showDiscoveryOverlay:function(){this.olay.show(this.$el,s.DISCOVERY,this.getOverlayOffset(),false,false,false)},clickedAway:function(){this.olay.isErrorOverlay()||this.olay.hide()}}})(jQuery,window);
(function(a,n){var c={},v="localStorage"in window&&!window.localStorage.discoveryRan,s,p=function(f,h){a(document).trigger("follow.fol",h)},i=function(f,h){a(document).trigger("unfollow.fol",h)},b=function(f,h){a(document).trigger("error.fol",h)},g=function(f){if(v&&f.getDiscoveryEnabled()){v=false;window.localStorage.discoveryRan=true;f.showDiscoveryOverlay()}};n.ebay.follow.Manager={init:function(){a(this).trigger("beforeInit");a(".fol-widget").each(function(f,h){n.ebay.follow.Manager.addWidget(h)});
a("body").click(function(f){var h=a(f.target).closest(".fol-widget").attr("id");s&&s!==h&&s in c&&c[s].clickedAway();s=h});a(this).trigger("afterInit")},addWidget:function(f){var h=f.id;if(h&&!(h in c)){var k=new ebay.follow.Widget(f);a(k).on("follow",p);a(k).on("unfollow",i);a(k).on("error",b);c[h]=k;g(k)}},getWidgetById:function(f){return c[f]}}})(jQuery,window);
$(function(){var a=ebay.follow.Manager,n=ebay.follow.Constants,c=ebay.follow.Util.getSearchParams(),v=c[n.SEARCH_PARAM_CSRF],s=window.location.hash;$(a).on("afterInit",function(){if(s&&v){var p=a.getWidgetById(s.substring(1));if(p){p.setCsrf(v);p.follow()}}});a.init()});
